FinalP.Web/Models/ApiRequest.cs
using Microsoft.AspNetCore.Mvc;
using static FinalP.Web.SD;
namespace FinalP.Web.Models
{
    public class ApiRequest
    {
        public ApiType ApiType { get; set; } = ApiType.GET;
        public string Url { get; set; }
        public object Data { get; set; }
        public string AccessToken { get; set; }
    }
}

FinalP.Web/Models/ErrorViewModel.cs
using System;

namespace FinalP.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FinalP.Web/Models/EtudiantDto.cs
using System.ComponentModel.DataAnnotations;

namespace FinalP.Web.Models
{
    public class EtudiantDto
    {
        public int EtudiantId { get; set; }
        
        public string EtudiantName { get; set; }
        
        public string Classename { get; set; }
        
        public int age { get; set; }
    }
}

FinalP.Web/Models/ResponseDto.cs
using System.Collections.Generic;

namespace FinalP.Web.Models
{
    public class ResponseDto
    {
        public bool IsSuccess { get; set; } = true;
        public object Result { get; set; }
        public string DisplayMessage { get; set; } = "";
        public List<string> ErrorMessages { get; set; }
    }
}

FinalP.Web/Controllers/EtudiantController.cs
using FinalP.Web.Models;
using FinalP.Web.Services;
using FinalP.Web.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Threading.Tasks;


namespace FinalP.Web.Controllers
{
    public class EtudiantController : Controller
    {
        public readonly IClasseService _classeService;
        public EtudiantController(IClasseService classeService)
        {
            _classeService = classeService;
        }

        public async Task<IActionResult> EtudiantIndex()
        {
            List<EtudiantDto> list = new List<EtudiantDto>();
            var response = await _classeService.GetAllEtudiantsAsync<ResponseDto>();
            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<EtudiantDto>>(Convert.ToString(response.Result));
            }
            return View(list);
        }

        public async Task<IActionResult> EtudiantCreate()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EtudiantCreate(EtudiantDto model)
        {
            if (ModelState.IsValid)
            { 
                var response = await _classeService.CreateEtudiantAsync<ResponseDto>(model);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(EtudiantIndex));
                }
            }
            return View(model);
            
        }

        public async Task<IActionResult> EditEtudiant(int etudiantId)
        {
            var response = await _classeService.GetEtudiantByIdAsync<ResponseDto>(etudiantId);
            if (response != null && response.IsSuccess)
            {
                EtudiantDto model = JsonConvert.DeserializeObject<EtudiantDto>(Convert.ToString(response.Result));
                return View(model);
            }
            return NotFound(); 
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditEtudiant(EtudiantDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await _classeService.UpdateEtudiantAsync<ResponseDto>(model);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(EtudiantIndex));
                }
            }
            return View(model);

        }
    

    public async Task<IActionResult> DeleteEtudiant(int etudiantId)
    {
        var response = await _classeService.GetEtudiantByIdAsync<ResponseDto>(etudiantId);
        if (response != null && response.IsSuccess)
        {
            EtudiantDto model = JsonConvert.DeserializeObject<EtudiantDto>(Convert.ToString(response.Result));
            return View(model);
        }
        return NotFound();
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteEtudiant(EtudiantDto model)
    {
        if (ModelState.IsValid)
        {
            var response = await _classeService.DeleteEtudiantAsync<ResponseDto>(model.EtudiantId);
            if (response.IsSuccess)
            {
                return RedirectToAction(nameof(EtudiantIndex));
            }
        }
        return View(model);

    }
}
}

FinalP.Web/Controllers/HomeController.cs
using FinalP.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FinalP.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FinalP.Web/Views/Etudiant/DeleteEtudiant.cshtml
@model FinalP.Web.Models.EtudiantDto
<form asp-action="DeleteEtudiant">
    <input asp-for="EtudiantId" hidden />
    <br />
    <div class="container border p-3">
        <h1 class="text-info">Delete Student</h1>
        <hr />
        <div class="row">
            <div class="col-2">
                <label asp-for="EtudiantName" class="custom-control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="EtudiantName" disabled class="form-control" />
            </div>
            <div class="col-2">
                <label asp-for="Classename" class="custom-control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Classename" disabled class="form-control" />
            </div>
            <div class="col-2">
                <label asp-for="age" class="custom-control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="age" disabled class="form-control" />
            </div>
            <div class="col-5 offset-2">
                <a asp-action="Index" class="btn-primary btn form-control ">Back to list</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-danger form-control" />
            </div>

        </div>
    </div>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

FinalP.Web/Views/Etudiant/EditEtudiant.cshtml
@model FinalP.Web.Models.EtudiantDto
<form asp-action="EditEtudiant">
<input asp-for="EtudiantId" hidden />
    <br />
    <div class="container border p-3">
        <h1 class="text-info">Edit Student</h1>
        <hr />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-2">
                <label asp-for="EtudiantName" class="custom-control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="EtudiantName" class="form-control" />
                <span asp-validation-for="EtudiantName" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="Classename" class="custom-control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Classename" class="form-control" />
                <span asp-validation-for="Classename" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="age" class="custom-control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="age" class="form-control" />
                <span asp-validation-for="age" class="text-danger"></span>
            </div>
            <div class="col-5 offset-2">
                <a asp-action="Index" class="btn-primary btn form-control ">Back to list</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Update" class="btn btn-info form-control" />
            </div>

        </div>
    </div>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

FinalP.Web/Views/Etudiant/EtudiantCreate.cshtml
@model FinalP.Web.Models.EtudiantDto
<form asp-action="EtudiantCreate">
    <br />
    <div class="container border p-3">
        <h1 class="text-info">Add Student</h1>
        <hr />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-2">
                <label asp-for="EtudiantName" class="custom-control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="EtudiantName" class="form-control" />
                <span asp-validation-for="EtudiantName" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="Classename" class="custom-control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Classename" class="form-control" />
                <span asp-validation-for="Classename" class="text-danger"></span>
            </div>
            <div class="col-2">
                <label asp-for="age" class="custom-control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="age" class="form-control" />
                <span asp-validation-for="age" class="text-danger"></span>
            </div>
            <div class="col-5 offset-2">
                <a asp-action="Index" class="btn-primary btn form-control ">Back to list</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-info form-control" />
            </div>

        </div>
    </div>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

FinalP.Web/Views/Etudiant/EtudiantIndex.cshtml
@model IEnumerable<FinalP.Web.Models.EtudiantDto>


<br />
<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">Student List</h1>
        </div>
        <div class="col text-end pt-1">
            <a asp-action="EtudiantCreate" class="btn btn-outline-info"><i class="fas fa-plus"></i>Add Student</a>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Nom
                </th>
              <th>
                    Classe
                </th>
                <th>
                    Age
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.EtudiantName
                    </td><td>
                        @item.Classename
                    </td><td>
                        @item.age
                    </td><td>
                        <a asp-action="EditEtudiant" class="btn btn-success" asp-route-etudiantId="@item.EtudiantId">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a asp-action="DeleteEtudiant" class="btn btn-danger" asp-route-etudiantId="@item.EtudiantId">
                            <i class="fas fa-trash"></i>
                        </a>
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

FinalP.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FinalP.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FinalP.Web</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/brands.min.css" integrity="sha512-G/T7HQJXSeNV7mKMXeJKlYNJ0jrs8RsWzYG7rVACye+qrcUhEAYKYzaa+VFy6eFzM2+/JT1Q+eqBbZFSHmJQew==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FinalP.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item pt-lg-2">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item pt-lg-2">
                            <a class="nav-link " asp-area="" asp-controller="Etudiant" asp-action="EtudiantIndex">Etudiant</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - FinalP.Web  Ala Ghabi on The building
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>